name: stream_taker
description: stream.take multi times,
version: 1.0.0
repository: https://github.com/AoEiuV020/stream_taker

environment:
  sdk: ^3.3.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
